package com.a2i;

import java.util.Iterator;

public class P002 {

    // Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    // By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


    public static void main(String[] args) {
        final int LIMIT = 4_000_000;
        final P002 sequence = new P002();

        Integer sum = 0;

        while (sequence.hasNext()) {
            Integer value = sequence.next();
            if (value > LIMIT) {
                break;
            }
            if (value % 2 == 0) {
                sum += value;
            }
        }
        System.out.println("Sum of even Fibonacci numbers < 4M = " + sum);

    }

    private Integer previous;
    private Integer current;

    private P002() {
        this.previous = -1;
        this.current = 1;
    }

    private Integer next() {
        Integer next = previous + current;
        previous = current;
        current = next;
        return next;
    }

    private boolean hasNext() {
        return true;
    }

    }
